version: 2

sphinx:
  builder: html
  configuration: documentation/doc/source/conf.py
  fail_on_warning: false

python:
   version: 3.7
   install:
      - requirements: requirements.txt
      - method: pip
        path: .
        exra_requirements: sphinx_requirements.txt
   system_packages: true
