virtualenv:
  system_site_packages: true
before_install:
- sudo apt-get install -qq python-numpy python-scipy python-nose python3-nose python-coverage python-matplotlib

language: python
python:
    - "3.6"

install: "pip install pytest; pip install -r requirements.txt"
script: "pytest tests/core"