language: python
python:
  - "3.6"

# install dependencies
install:
  - python setup.py install
  #- pip install -e /home/travis/build/pyrates-neuroscience/PyRates
  - pip install --ignore-installed pytest
  - pip install --ignore-installed -r requirements.txt

# run tests
script:
  - pytest tests/core/