# -*- coding: utf-8 -*-
#
#
# PyRates software framework for flexible implementation of neural
# network model_templates and simulations. See also:
# https://github.com/pyrates-neuroscience/PyRates
#
# Copyright (C) 2017-2018 the original authors (Richard Gast and
# Daniel Rose), the Max-Planck-Institute for Human Cognitive Brain
# Sciences ("MPI CBS") and contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
# CITATION:
#
# Richard Gast and Daniel Rose et. al. in preparation
"""JAX backend.  Generates :code:`jax.numpy` source code for the model RHS,
JIT-compiles the resulting function, and integrates ODEs via :code:`diffrax`
when available — with a scipy fall-back that handles JAX↔NumPy conversion
at the integrator boundary.

Differences from the numpy default that warrant a dedicated backend:

* JAX arrays are immutable, so the standard :code:`dy[i] = ...` lines that
  the base code generator emits would error at JIT-trace time.  We override
  :code:`add_var_update` to emit JAX functional updates (:code:`dy = dy.at[i]
  .set(...)`) instead.
* The generated function is decorated with :code:`@jax.jit` so subsequent
  calls (parameter fitting, sweeps) reuse the compiled trace.
* :code:`get_var` returns :code:`jax.numpy` arrays so the JIT trace sees
  consistent types across calls.
"""

# pyrates internal imports
from ..base import BaseBackend
from ..computegraph import ComputeVar
from .jax_funcs import jax_funcs

# external imports
import numpy as np
from typing import Callable, Iterable, Optional, Dict, List, Tuple, Union

# meta infos
__author__ = "Richard Gast"
__status__ = "development"


# JAX needs to be importable but we delay heavy initialisation until the
# backend is instantiated so users without JAX installed can still use the
# rest of PyRates.
try:
    import jax
    import jax.numpy as jnp
    _JAX_AVAILABLE = True
except ImportError:                                                          # pragma: no cover
    jax = None
    jnp = None
    _JAX_AVAILABLE = False


class JaxBackend(BaseBackend):
    """Code-generating JAX backend.

    Notes
    -----
    Requires :code:`jax` (and, for the recommended :code:`solver='diffrax'`
    path, the :code:`diffrax` package).  Set :code:`float_precision='float64'`
    if you need x64 precision — the backend will enable :code:`jax_enable_x64`
    for the whole process automatically.
    """

    # In addition to the base trio, JaxBackend ships a JIT-compiled
    # adaptive integrator via diffrax.diffeqsolve (solver='diffrax').
    SUPPORTED_SOLVERS = ('euler', 'heun', 'scipy', 'diffrax')

    # ``scipy.sparse.csr_matrix`` and JAX tracers don't compose.
    SUPPORTS_SPARSE_JACOBIAN = False
    # The ring-buffer edge-delay code generated by ComputeGraph mutates a
    # buffer in-place each step; JAX functional updates make every call get
    # back the original (unchanged) buffer.  Users should use the
    # DDEHistory / ``past(x, tau)`` path instead.
    SUPPORTS_EDGE_DELAY_BUFFER = False

    def __init__(self,
                 ops: Optional[Dict[str, str]] = None,
                 imports: Optional[List[str]] = None,
                 **kwargs) -> None:

        if not _JAX_AVAILABLE:
            raise ImportError(
                "JaxBackend requires the `jax` package. Install with "
                "`pip install 'jax[cpu]' diffrax` (or `jax[cuda]` for GPU)."
            )

        # x64 mode is global to the JAX process — opt-in via float_precision
        if kwargs.get('float_precision', 'float32') == 'float64':
            jax.config.update("jax_enable_x64", True)

        # merge default jax_funcs with any user-provided ops
        all_ops = jax_funcs.copy()
        if ops:
            all_ops.update(ops)

        super().__init__(ops=all_ops, imports=imports, **kwargs)
        # replace the default "from numpy import pi, sqrt" with a JAX equivalent
        # (the base class always sets this as the first import line)
        self._imports[0] = "from jax.numpy import pi, sqrt"
        # ensure `jit` is available inside the generated module
        self.add_import("from jax import jit")
        self.add_import("import jax.numpy as jnp")

    # ---------------------------------------------------------------------
    #  Variable conversion: numpy → jax.numpy
    # ---------------------------------------------------------------------
    def get_var(self, v: ComputeVar):
        """Return either a :code:`jax.numpy` array or a NumPy 0-d for the
        given ComputeVar.

        Conversion policy (informed by review §3.6):

        * **0-d / scalar constants** (e.g. ``tau``, ``eta``) are left as
          plain NumPy 0-d arrays.  JAX accepts them as JIT inputs without
          re-tracing (the trace cache keys by abstract dtype+shape, not by
          concrete value), so wrapping in :code:`jnp.asarray` here would
          add ~100 µs of per-``get_var`` work for no runtime benefit.
        * **Multi-dimensional arrays** (e.g. ``dy``, weight matrices) are
          converted with :code:`jnp.asarray`.  ``dy`` in particular *must*
          be a JAX array because the generated code does
          ``dy = dy.at[i].set(...)``, which is JAX-only.

        Time variables stay as NumPy regardless — they are produced by the
        solver and only cross the JAX boundary once per scan invocation.

        NOTE on the review's :code:`static_argnums` suggestion: marking
        constants as static would force a re-trace on every new concrete
        value, which is catastrophic for parameter sweeps (~30 ms re-trace
        per sweep point vs. ~50 µs for the dynamic-arg path).  We
        intentionally do *not* take that route.
        """
        arr = super().get_var(v)
        if v.name in ('t', 'time'):
            return arr
        # 0-d (scalar) constants: leave as NumPy — JAX accepts them at the
        # JIT boundary and converts lazily without re-tracing.
        if arr.ndim == 0:
            return arr
        # Vector / matrix arrays need to be JAX to support `.at[...]`.
        return jnp.asarray(arr)

    # ---------------------------------------------------------------------
    #  Code generation: functional index-updates instead of in-place writes
    # ---------------------------------------------------------------------
    def add_var_update(self,
                       lhs: ComputeVar,
                       rhs: str,
                       lhs_idx: Optional[str] = None,
                       rhs_shape: Optional[tuple] = ()):
        """Emit a JAX-safe variable update.

        Without an index this collapses to a plain Python rebind, which works
        for both NumPy and JAX.  With an index we cannot do
        :code:`a[i] = expr` on a JAX array, so we emit
        :code:`a = a.at[i].set(expr)` instead.
        """
        lhs_name = lhs.name
        if lhs_idx:
            idx, _ = self.create_index_str(lhs_idx, apply=False)
            self.add_code_line(f"{lhs_name} = {lhs_name}.at[{idx}].set({rhs})")
        else:
            self.add_code_line(f"{lhs_name} = {rhs}")

    # ---------------------------------------------------------------------
    #  Decorate the generated function with @jit (except for DDE)
    # ---------------------------------------------------------------------
    def _add_func_call(self, name: str, args: Iterable, return_var: str = 'dy'):
        """Apply ``@jit`` to the generated function header.

        DDE functions are *not* JIT-decorated: they take a Python
        :class:`DDEHistory` callable through ``hist``, and ``DDEHistory.__call__``
        does ``t = float(t)`` which raises ``ConcretizationTypeError`` when JAX
        traces it.  The JIT win for DDE is limited anyway because the
        ``scipy.integrate.ode`` driver loops in Python and calls the RHS
        function one step at a time — there is no inner loop to fuse.
        The function still uses :mod:`jax.numpy` ops (``zeros``, ``.at[...]``)
        and therefore runs correctly in eager mode.
        """
        args = list(args)
        if 'hist' not in args:
            self.add_code_line('@jit')
        self.add_code_line(f"def {name}({','.join(args)}):")

    # ---------------------------------------------------------------------
    #  Jacobian-emission hooks: functional updates instead of in-place writes
    # ---------------------------------------------------------------------
    def declare_local_array_imports(self) -> None:
        """Pull ``zeros`` from :mod:`jax.numpy` (not numpy)."""
        self.add_import("from jax.numpy import zeros")

    def emit_local_array_assign(self, name: str, indices: tuple, expr: str) -> None:
        """Emit ``name = name.at[i, j].set(expr)`` (JAX arrays are immutable)."""
        idx_str = ', '.join(str(i) for i in indices)
        self.add_code_line(f"{name} = {name}.at[{idx_str}].set({expr})")

    # ---------------------------------------------------------------------
    #  ODE solvers
    # ---------------------------------------------------------------------
    def _solve(self, solver: str, func: Callable, args: tuple, T: float, dt: float, dts: float,
               y0: np.ndarray, t0: np.ndarray, times: np.ndarray, **kwargs) -> np.ndarray:

        self._validate_solver(solver)

        # cast initial value to JAX so the JIT-compiled function gets the right type
        y0 = jnp.asarray(y0)

        if solver == 'diffrax':
            return self._solve_diffrax(func, args, T, dt, y0, t0, times, **kwargs)

        if solver == 'scipy':
            from ..base.base_backend import DDEHistory
            if len(args) > 0 and isinstance(args[0], DDEHistory):
                # DDEs need history-buffer mutation, which is not currently
                # JIT-safe — fall back to the base scipy DDE solver.
                return super()._solve_scipy_dde(func, args, T, dt, y0, t0, times, **kwargs)
            return self._solve_scipy(func, args, T, dt, y0, t0, times, **kwargs)

        if solver == 'euler':
            return self._solve_euler(func, args, T, dt, dts, y0, t0)

        # solver == 'heun' (the only remaining case after _validate_solver)
        return self._solve_heun(func, args, T, dt, dts, y0, t0)

    def _solve_diffrax(self, func: Callable, args: tuple, T: float, dt: float,
                       y0: 'jnp.ndarray', t0: 'np.ndarray', times: np.ndarray, **kwargs):
        """Adaptive integration via :code:`diffrax.diffeqsolve`."""
        try:
            import diffrax
        except ImportError as e:                                             # pragma: no cover
            raise ImportError(
                "solver='diffrax' requires the `diffrax` package. "
                "Install with `pip install diffrax`."
            ) from e

        # diffrax expects f(t, y, args) -> dy.  The PyRates-generated function
        # has signature f(t, y, dy_buf, *params); args[0] is the original dy
        # buffer and the remaining entries are the model parameters.  We pass
        # the full args tuple through diffrax and unpack inside term_fun.
        def term_fun(t, y, params):
            return func(t, y, *params)

        method_name = kwargs.pop('method', 'Tsit5')
        try:
            solver_cls = getattr(diffrax, method_name)
        except AttributeError:
            solver_cls = diffrax.Tsit5
        rtol = kwargs.pop('rtol', 1e-6)
        atol = kwargs.pop('atol', 1e-8)
        kwargs.pop('first_step', None)

        ts_eval = jnp.asarray(times)
        sol = diffrax.diffeqsolve(
            diffrax.ODETerm(term_fun),
            solver_cls(),
            t0=float(t0), t1=float(T), dt0=float(dt),
            y0=y0, args=tuple(args),
            saveat=diffrax.SaveAt(ts=ts_eval),
            stepsize_controller=diffrax.PIDController(rtol=rtol, atol=atol),
            max_steps=kwargs.pop('max_steps', 1_000_000),
        )
        return np.asarray(sol.ys)

    def _solve_scipy(self, func: Callable, args: tuple, T: float, dt: float,
                     y0: 'jnp.ndarray', t0: 'np.ndarray', times: np.ndarray, **kwargs):
        """scipy.solve_ivp wrapper that converts at the integrator boundary."""
        from scipy.integrate import solve_ivp
        kwargs['t_eval'] = times

        y_dtype = jnp.result_type(y0)
        # ``t`` must stay real even when ``y`` is complex — jnp.interp (and
        # other indexing-by-time ops) reject complex ``x`` values.  PyRates'
        # BaseBackend.get_var already declares ``t`` / ``time`` as the real
        # counterpart of the complex precision; preserve that here.
        if y_dtype == jnp.complex64:
            t_dtype = jnp.float32
        elif y_dtype == jnp.complex128:
            t_dtype = jnp.float64
        else:
            t_dtype = y_dtype

        def f(t, y):
            return np.asarray(
                func(jnp.asarray(t, dtype=t_dtype), jnp.asarray(y, dtype=y_dtype), *args)
            )

        results = solve_ivp(fun=f, t_span=(float(t0), float(T)),
                            y0=np.asarray(y0), first_step=dt, **kwargs)
        return results['y'].T

    def _solve_euler(self, func: Callable, args: tuple, T: float, dt: float, dts: float,
                     y: 'jnp.ndarray', t0) -> np.ndarray:
        """Forward Euler integration fused into a single XLA kernel via :code:`jax.lax.scan`.

        Layout:
            outer scan runs once per stored sample (``store_steps`` iterations
            total); inner scan does ``store_step`` Euler updates between stored
            samples.  Each outer iteration emits the *starting* y for that
            block, matching the semantics of the previous Python-loop
            implementation (``state_rec[0] = y_initial``, ``state_rec[1] = y``
            after ``store_step`` updates, …).

        :code:`args` is the full PyRates parameter tuple including the dy
        buffer at index 0; it is captured by closure into the scan body and
        traced as JAX constants on the first call.

        ``t`` is passed to the RHS as an *integer step counter*, matching
        :meth:`BaseBackend._solve_euler` exactly.  This is the convention the
        PyRates code generator targets for fixed-step solvers (``dt_adapt=False``):
        input-array plumbing emits ``u_timed_input = u_input[t]`` and DDE
        history extraction uses ``hist(t*dt - d)``.  JAX strictly requires
        integer indices, so a float ``t`` would crash the input path.
        """
        steps = int(np.round(T / dt))
        store_steps = int(np.round(T / dts))
        store_step = int(np.round(dts / dt))

        y0 = jnp.asarray(y)
        t0_val = jnp.asarray(t0)
        if t0_val.dtype.kind == 'f':                     # int convention for euler
            t0_val = t0_val.astype(jnp.int32)
        increment = jnp.asarray(1, dtype=t0_val.dtype)
        args_t = tuple(args)

        def inner_step(carry, _):
            t, y = carry
            rhs = func(t, y, *args_t)
            return (t + increment, y + dt * rhs), None

        def outer_step(carry, _):
            t_start, y_start = carry
            (t_end, y_end), _ = jax.lax.scan(inner_step, (t_start, y_start), None,
                                             length=store_step)
            return (t_end, y_end), y_start

        _, ys = jax.lax.scan(outer_step, (t0_val, y0), None, length=store_steps)
        return np.asarray(ys)

    def _solve_heun(self, func: Callable, args: tuple, T: float, dt: float, dts: float,
                    y: 'jnp.ndarray', t0) -> np.ndarray:
        """Heun's method (predictor-corrector RK2), fused via :code:`jax.lax.scan`.

        Identical scaffolding to :meth:`_solve_euler`; only the inner update
        differs (two RHS evaluations per step instead of one).  See
        :meth:`_solve_euler` for the integer-step-counter ``t`` convention.
        """
        steps = int(np.round(T / dt))
        store_steps = int(np.round(T / dts))
        store_step = int(np.round(dts / dt))

        y0 = jnp.asarray(y)
        t0_val = jnp.asarray(t0)
        if t0_val.dtype.kind == 'f':
            t0_val = t0_val.astype(jnp.int32)
        increment = jnp.asarray(1, dtype=t0_val.dtype)
        args_t = tuple(args)

        def inner_step(carry, _):
            t, y = carry
            k1 = func(t, y, *args_t)
            y_pred = y + dt * k1
            k2 = func(t + increment, y_pred, *args_t)
            return (t + increment, y + 0.5 * dt * (k1 + k2)), None

        def outer_step(carry, _):
            t_start, y_start = carry
            (t_end, y_end), _ = jax.lax.scan(inner_step, (t_start, y_start), None,
                                             length=store_step)
            return (t_end, y_end), y_start

        _, ys = jax.lax.scan(outer_step, (t0_val, y0), None, length=store_steps)
        return np.asarray(ys)
